### ISSUE TITLE
Basic Shooter Subsystem

### ISSUE THREAD

**Issue by tunapro1234** [team-nf/24-regional-robocode#1]
Shooter için temel kodların yazılımı tamamlanacak. Aranan temel özelliklerin listesi:
- Robotta kullanılacak tüm motorların ve motor sürücülere uygun kodlanmış olması
- Shooter açı ayarlama PID sistemi
- Shooterın sabit olduğu profilleri ileri ve geri oynatmak için gerekli fonksiyonlar
- Shooter  başını pnömatik ile açıp kapatma için gerekli fonksiyonlar
- Topu ateşlemek için gerekli motorları çalıştıracak fonksiyonlar
- Topu shooterın içine almak için gerekli motorları çalıştıracak fonksiyonlar
- FINAL TUŞ ATAMALARI INTAKE SISTEMI TAMAMLANDIKTAN SONRA YAPILACAK

Bu özellikler koda eklendikten sonra, shooter için 3 mod belirleyip bunları tuşlara atayabiliriz (yine, intake bittikten sonra). Bu 3 mod, intakeden alım modu, uzağa atış modu ve bırakma modu olabilir. Tuşlara atamak için de ya 3 tuş kullanılabilir ya da intake/shoot arasında toggle için bir tuş ve shoot modları arasında toggle için ayrı bir buton kullanılabilir. Tuş kombinasyonunun belirlenmesi için driver, yuşa ve tunayla iletişim kurulmalı.

**Comment by yehpop** [comment]
Bu issuelar çok geçmişte kaldı ben yokum diye herhalde ama hiç güncellenmemiş. Pnömatikler iptal tasarım farklı fasa fiso subsystem işleri bitireli çok oldu branch bağlıyorum.

**Comment by yehpop** [comment]
branchi değiştiremedim eski branch kapandı ancak. [subsystems-dev.](https://github.com/team-nf/24-regional-robocode/tree/subsytems-dev) yalnızca pid ayarları ve debug/test kaldı onun için de şuraya bakınız -> #8
