### ISSUE TITLE
Basic Intake Subsystem

### ISSUE THREAD

**Issue by tunapro1234** [team-nf/24-regional-robocode#2]
Intake için temel kodların yazılımı. Aranan özelliklerin listesi:
- Robotta kullanılacak tüm motorların ve motor sürücülere uygun kodlanmış olması
- Intake'in açısını ayarlamak için gerekli PID sistemleri
- Topu içeri alan motorları sürmek için gerekli fonkiyonlar
- Shooter sistemiyle birleştirilerek tuş atamaları yapılacak

**Comment by yehpop** [comment]
[bu commit](https://github.com/team-nf/24-regional-robocode/commit/c3510d79ec1a4e673e49ce8f743eed269dfcfac6) temel intake subsystem şartlarını karşılıyordur. branchin güncel hali kesinlikle karşılıyor. Kapatıyorum issue'yu PID ayarlaması kaldı yalnızca -> #8
