### ISSUE TITLE
Basic Climbing Subsystem

### ISSUE THREAD

**Issue by tunapro1234** [team-nf/24-regional-robocode#3]
Climbing için temel kodların yazılımı. Aranan özelliklerin listesi:

- Robotta kullanılacak tüm motorların ve motor sürücülere uygun kodlanmış olması
- İstenilen uzunlukta açılmayı sağlamak için gerekli PID sistemleri
- Sistemi açıp kapatmak için gerekli tuş atamaları

Çalışma Mekanizması hakkında daha fazla bilgi edinilmeli.

Atanacak tuş toggle olmalı (tuna).

**Comment by yehpop** [comment]
subsystems-dev branchini linkledim. Testler Debug yapmalar ve PID işleri kaldı tırmanma için pid ihtiyacımız olur mu düşünüyorum -> #8
